wip: Personal/rzaracota/fix pipeline tests
smartsheet/smartsheet-csharp-sdk pull request #49
Opened 2023-08-07 21:50 UTC by rzaracota

2023-09-11 18:41 UTC, timothodge commented
Fixed up the PR to deserialize RestSharp responses, unwrap AggregateExceptions, and help pass back correct error code/messages for mock API tests that are testing error paths.

2023-09-12 17:37 UTC, timothodge reviewed
I approve of these changes but I would appreciate @lifebeyondfife or @pratik136 to also take a look before we move forward.

2023-09-15 12:29 UTC, pratik136 approved these changes, later dismissed
The changes look good to me. 🎉

2023-09-19 22:02 UTC, lifebeyondfife approved these changes, later dismissed
Looks good 😄

2023-09-19 23:12 UTC, timothodge approved these changes, later dismissed

2023-09-27 00:11 UTC, pratik136 requested changes

2023-09-27 00:11 UTC, pratik136 commented on .github/workflows/publish.yml
> +       smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
Referencing the old path `.../travis_scripts/...`. 

Change to 
```sh
    smartsheet-sdk-tests/ci_scripts/install_wiremock.sh
    smartsheet-sdk-tests/ci_scripts/start_wiremock.sh
```

2023-09-27 16:01 UTC, pratik136 approved these changes

2023-09-27 16:03 UTC, merged